name: Automated Navigation Library Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Updates
      run: sudo apt-get update
    - name: Install Build Tools
      run: sudo apt install build-essential libtool autoconf unzip wget
    - name: Install Eigen
      run: sudo apt install libeigen3-dev
    - name: Install CMake
      run: sudo apt-get install cmake
    - name: Create Build Directory and Run CMake
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    - name: Build Project
      run: cmake --build build --target all --config Release -- -j4
    - name: Move to Build Folder
      run: cd build
    - name: Run Unit Tests
      run: ./test-navigation-library
